#!/usr/bin/env python3

#
# Run the test, check it completed successfully
#

from boututils.run_wrapper import shell, shell_safe, launch_safe
from boutdata.collect import collect
from sys import stdout, exit
import numpy as np

shell("ln -s ../../../hermes-3 hermes-3")

# Run the case
s, out = launch_safe("./hermes-3", nproc=1, mthread=1, pipe=True)
with open("run.log", "w") as f:
  f.write(out)

# Collect the density and pressure
n = collect("Nh", path="data")
p = collect("Ph", path="data")

# Check that the density is changing in time
assert np.amax(np.abs(n[-1,2:-2,:,:] - n[0,2:-2,:,:])) > 0.05

# Calculate temperature
T = p / n

# Check that the temperature is not changing
assert np.amax(np.abs(T[-1,2:-2,:,:] - T[0,2:-2,:,:])) < 1e-6

exit(0)
