#!/usr/bin/env python3

#
# Run the test, check it completed successfully
#

from boututils.run_wrapper import shell, shell_safe, launch_safe
from boutdata.collect import collect
from sys import stdout, exit
import numpy as np

shell("ln -s ../../../hermes-3 hermes-3")

# Run the case
s, out = launch_safe("./hermes-3", nproc=1, mthread=1, pipe=True)
with open("run.log", "w") as f:
  f.write(out)

# Collect the density and pressure
n = collect("Nh", path="data")
p = collect("Ph", path="data")

# Check that the density is not constant at the start
assert np.amax(n[0,2:-2,:,:]) - np.amin(n[0,2:-2,:,:]) > 0.1

# Check that the density is almost constant at the end
assert np.amax(n[-1,2:-2,:,:]) - np.amin(n[-1,2:-2,:,:]) < 1e-3

# Total number of particles conserved
assert abs(np.sum(n[-1, 2:-2,:,:]) - np.sum(n[0, 2:-2,:,:])) < 1e-3

# Total thermal energy decreasing (some lost to viscosity)
assert np.sum(p[-1, 2:-2,:,:]) <= np.sum(p[0, 2:-2,:,:])

exit(0)
