
BOUT_TOP	= ../../..

MODULE_DIR	= ..

SUB_NAME	= src
TARGET		= hermes-3

SOURCEC		= component.cxx component_scheduler.cxx ionisation.cxx radiation.cxx \
		  div_ops.cxx \
                  neutral_mixed.cxx full_velocity.cxx \
		  evolve_ne.cxx \
                  isothermal_electrons.cxx \
		  diamagnetic_drift.cxx

include $(BOUT_TOP)/make.config
