
BOUT_TOP	= ../../..

MODULE_DIR	= ..

SUB_NAME	= src
TARGET		= hermes-3

SOURCEC		= component.cxx component_scheduler.cxx ionisation.cxx radiation.cxx \
                  neutral_mixed.cxx

include $(BOUT_TOP)/make.config
