
BOUT_TOP	= ../../..

MODULE_DIR	= ..

SUB_NAME	= src
TARGET		= hermes-3

SOURCEC		= component.cxx component_scheduler.cxx ionisation.cxx radiation.cxx \
		  div_ops.cxx loadmetric.cxx \
                  neutral_mixed.cxx full_velocity.cxx \
		  evolve_density.cxx vorticity.cxx \
                  evolve_pressure.cxx \
                  evolve_momentum.cxx \
                  isothermal.cxx quasineutral.cxx \
		  diamagnetic_drift.cxx \
                  sheath_closure.cxx \
                  fixed_fraction_ions.cxx \
                  sound_speed.cxx zero_current.cxx

include $(BOUT_TOP)/make.config
